name: sugina
version: 0.1.0.0
git: https://gitlab.com/kakitsubata/sugina.git
license: BSD3
author: "The Sugina Development Group"
copyright: "2018-2019 The Sugina Development Group"

default-extensions:
- GADTs
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell
- ViewPatterns

extra-source-files:
- README.md

# Package metadata
synopsis: Server configurations and files by Sugina Development Group.
category: Web

description: See package README for details.

dependencies:
- aeson >= 1.4 && < 1.5
- base >= 4.9.1.0 && < 5
- bytestring >= 0.9 && < 0.11
- containers
- esqueleto >= 2.6 && < 3
- file-embed
- http-types
- monad-logger >= 0.3 && < 0.4
- persistent >= 2.9 && < 2.10
- persistent-sqlite >= 2.9 && < 2.10
- persistent-template >= 2.5 && < 2.9
- random >= 1.1 && < 2
- shakespeare >= 2.0 && < 2.1
- text >= 0.11 && < 2.0
- time
- transformers >= 0.5 && < 1
- wai-extra >= 3.0 && < 3.1
- warp >= 3.0 && < 3.3
- yesod >= 1.6 && < 1.7
- yesod-auth >= 1.6 && < 1.7
- yesod-auth-oauth2 >= 0.6
- yesod-core >= 1.6 && < 1.7
- yesod-form >= 1.6 && < 1.7

library:
  source-dirs: lib
  ghc-options:
  - -funbox-strict-fields
  - -O
  - -Wall
  - -Werror
  dependencies:
  - aeson >= 1.4 && < 1.5

executables:
  sugina:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -funbox-strict-fields
    - -O
    - -Wall
    - -Werror
    dependencies:
    - sugina
